BatNames:
- Man
- Rouge
- Flutter Me Timbers
- Batty
- Dracula
- Batt
- Bob the Bat
- Fang
- Vlad
- Batosity
- Al-Ghul
- Nosferatu
- Fledermaus
- Bitey
- Diablerie
- Bella
- Max
- Lee
- Tony
- Bax
- Lucifer
- Dullus
- Skotardus
- Thanatos
- Mortus
- Tenebrus
- Noisy
- Charline
- Rosfrath
- Bastion
- Luna
- Maya
- Mayotis
- Batrisha
- Ralph
- Bertie
ChickenNames:
- Picasso
- Fingerlicken
- Licken
- Batter
- Dinner
- Lunch
- Foghorn
- Leghorn
- Boo
- Alfred
- Ginger
- Camilla
- Robot
- Cluck
- Clucky
- Mike
- Rocky
- Gregory
- Peck
- Little
- Penny
- Rubber
- Nugget
- Leg
- Wing
- Fried
- Kentucky
- Toktok
- Flatfoot
- Kurusa
- Muragira
CowNames:
- Gertrude
- Bessie
- Whack Angus
- Angus
- Whack
- Beefy
- Ermintrude
- Colleen
- Betsy
- Patty
- Anna
- Molly
- Darcy
- Elli
- Ethel
- Nelly
- Beth
- Daisy
- Buttercup
- Achelous
- Audhumla
- Bat
- Blue
- Bully
- Chaldan
- Damona
- Dhol
- Dun
- Elsie
- Flossie
- Fuwch
- Glas
- Hathor
- Hesat
- Lo
- Mehturt
- Milka
- Nandini
- Sechat
- Sentait
- Taurus
- Vache
- Annabelle
- Klara
- June
- Johnny
- Kate
- Boy
- Dixie
- Marigold
IronGolemNames:
- Fat Tony
- Bruce
- Cranky
- Nutty
- Bolts
- Bouncer
- Bob
- Jim
- Defender
- Protector
- Cranky
- Rob
- Boris
- Clunk
- Clank
- Clang
- Pummela
- Thonk
- Thumper
- Sergeant
- Bash
- Norton
- Eibmoz
- Slam
- Thwomp
- Chef
- Steelton
- Homie McSteel
- Johnny Iron
- Android 16
- Bot
MooshroomNames:
- Ultus
- Fungus
- Awesomnitetrus
- Ermintruffle
- Shroom
- Sir Shroom
- Madam Shroom
- Shroomie
- Mushles
- Manitar
- Sampion
- Kep
- Fatara
- Sunk
- Gobelek
- Ondo
- Reeb
- Masaruma
- Gooba
- Bolet
- Mogu
- Gliva
- Houba
- Champignon
- Paddestoel
- Fungoy
- Funguy
- Fungi
- Sumulpot
- Sieni
- Cogumelo
OcelotNames:
- Tiddles
- Tigger
- Midge
- Mo
- Fluffy
- Oscar
- Max
- Tiger
- Sam
- Misty
- Simba
- Coco
- Chloe
- Lucy
- Missy
- Puss
- Smokey
- Bella
- Molly
- Milo
- Angel
- Lily
- Kitty
- Ginger
- Charlie
- Poppy
- Smudge
- Millie
- Daisy
- Jasper
- Felix
- Alfie
- Shadow
- Minka
- Moritz
- Charly
- Susi
- Lisa
- Blacky
- Muschi
- Minou
- Grisou
- Ti-Mine
- Caramel
- Mimi
- Pacha
- Charlotte
- Minette
- Chanel
- Dama
- Ancella
- Briseide
- Folco
- Jack
- Barsik
- Boris
- Vaska
PigNames:
- Porky
- Piggy
- Miss Piggy
- Pumba
- Wilbur
- Hamm
- Percy
- Peppa
- Ace
- Fener
- Freddy
- Gaston
- Josephine
- Gouger
- Snouter
- Rooter
- Tusker
- Gryllus
- Gub
- Habeas
- Hamilton
- Hen
- Henry
- Jodie
- Johnny
- Jimmy
- Jaimie
- Jared
- Jason
- Justin
- Karnac
- Kimmy
- Lester
- Robinson
- Mercy
- Napoleon
- Major
- Olivia
- Pequenious
- Pig
- Pigling
- Pigoons
- Poppleton
- Positive
- Piggy
- Sam
- Snowball
- Squealer
- Toby
- Toot
- Puddle
- Zhu
SheepNames:
- Dolly
- Mary
- Bill
- Woolly
- Adam
- Woolworth
- Jumper
- Skape
- Haroof
- Vochkar
- Koyun
- Ardi
- Avechka
- Ovella
- Yang
- Ovca
- Safo
- Lammas
- Tupa
- Lamma
- Mouton
- Schaf
- Provata
- Ghetum
- Sophie
- Domba
- Pecore
- Hitsuji
- Kuri
- Oves
- Aita
SquidNames:
- Squidlington
- Squidward
- Squiddles
- Kraken
- Ood
- Haploteuthis
- Ferox
- Kalmaro
- Kalmaar
- Kalmari
- Calmar
- Lula
- Titenfisch
- Kalamari
- Skvida
- Kalma
- Tintahal
- Smokkfiskur
- Ika
- Ereyagi
- Balasuva
- Ojing
- Eo
- Lollingo
- Kalmars
- Kalmaras
- Sotong
- Klamari
- Akkar
- Kalamarnica
- Calamar
WolfNames:
- Bach
- Wolfgang
- Max
- Buddy
- Molly
- Maggie
- Jake
- Daisy
- Lucy
- Rocky
- Bailey
- Sadie
- Ginger
- Chloe
- Sophie
- Buster
- Zoe
- Cody
- Charlie
- Bear
- Jack
- Princess
- Bella
- Angel
- Toby
- Lady
- Sasha
- Duke
- Lucky
- Abby
- Sam
- Roxy
- Missy
- Harley
- Brandy
- Coco
- Shadow
- Annie
- Katie
- Rusty
- Samantha
- Casey
- Murphy
- Gracie
- Sammy
- Bruno
- Maximus
- Luke
- Mickey
- Romeo
BlazeNames:
- Death
- Firestarter
- Burnie
- Fire Breather
- Firefly
- Blazer
- Inferno
- Fuego
- Moto
- Eld
- Ti
- Angi
- Yangin
- Lua
- Tan
- Vuur
- Krak
- Yangin
- Sua
- Agni
- Huo
- Vatra
- Ohen
- Brand
- Sunog
- Palo
- Feu
- Lume
- Fotia
- Aga
- Dife
- Tuz
- Eldur
CaveSpiderNames:
- Trogloraptor
- Dolloff
- Hickmania
- Troglodyte
- Kauai
- Liphistius
- Batuensis
- Lygromma
- Anops
- Bourneti
- Mendari
- Nesticella
- Marapu
- Ochyroceratidae
- Physocyclus
- Globosus
- Progradungula
- Carraiensis
- Psechridae
- Sinopoda
- Scurion
- Spelungula
- Cavernicola
- Tartarus
- Genus
- Mullamullangensis
- Theridion
- Strepitus
- Carrai
- Nelson
- Mullamullang
CreeperNames:
- JIMJUM - Green Edition
- Mr. T... NT
- Sir Creepalot
- ssssSSSSSSS
- Creeps
- Creepy
- Creepah
- It'll be fine...
- James
- Bertie
- Creeples
- Come closer...
- I just want a hug...
- Rick Asssssssstley
- Da Bomb
- I'm a cow really... come closer...
- Cuddlesssssssss
- Ssssssssteve
- Morshu
- Stanley
- Ontplof
- Lehertu
- Paddervassa
- Bisforita
- Explotar
- Bozar
- Plavatama
- Sumabog
- Rayata
- Visfota
- Felrobban
- Sprungio
- Meledak
- UltiBoom
EnderDragonNames:
- GAHHHHHHD
- Santa Claus
- I'muh DRAYYGON
- Your eventual cause of Death...
- Bob
- Akhir
- Lord of The End
- Owari
- Fafnir
- Endriago
- Jabberwock
- Ancalagon
- Glaurung
- Scatha
- Smaug
- Chrysophylax Dives
- Nepomuk
- Frau Mahlzahn
- Kalessin
- Orm
- Orm Embar
- Orm Irian
- Tehanu
- Faranth
- Mnementh
- Ramoth
- Katla
- Bryagh
- Gorbash
- Secoh
- Smrgol
EndermanNames:
- Daddy longlegs
- By the time you've read this I'm probably already chasing you...
- No.
- Gerroff muy laaarnd!
- Stares
- Look down...
- End
- Endy
- Endus
- Endus McEnd
- The Face Of Death
- Look into my eyes...
- Bob
- John
- Ender Claus
- Rick
- Pabaiga
- Jeff
- Einde
- Fund
- Mbarim
- Qëllim
- Kufi
- Anë
- Përfundoj
- Mbyll
- Mbaroj
- Ndal
- Vdes
- վերջ
- մնացորդ
- նպատակ
- արդյունք
- ծայր
- հետեվանք
- Son
- Xitam
- Uc
- Axır
- əcəl
- Intəha
- Ayaq
- Kam
- əncam
- Kənarə
- Bitirmək
- Qurtarmaq
- Bitmək
- Kəsilmək
- Tamamlamaq
- Tükənmək
- Amaiera
- Канец
- Kрай
- цел
- завършек
- резултат
- изчерпване
- смърт
- привършване
- краен
- последен
- свършвам
- приключвам
- завършвам
- Final
- 结束
- 端
- 终止
- 终
- 完结
- 尾
- 末
- 底
- 终端
- 末尾
- 终
- 终点
- Kraj
- Završetak
- Svršetak
- Rep
- Izmak
- Završiti
- Prestati
- Svršiti
- Minuti
- Konec
- Závěr
- část
- Strana
- Okraj
- špička
- Polovina
- Zbytek
- Skončit
- Končit
- Einde
- Eind
- Uiteinde
- Afloop
- Doel
- Slot
- Punt
- Besluit
- Oogmerk
- Eindigen
- Aflopen
- Ophouden
- Fino
- Lõpp
- Ots
- Eesmärk
- Lõppemine
- Piir
- Tulemus
- Surm
- Lõpetama
- Lõppema
GhastNames:
- Floating Paper Bag
- Hilda
- Testifighast
- Ghoul
- Ghost
- Ghast
- Spook
- Fantazmë
- ուրվական
- Xəyal
- прывід
- গোস্ট
- Duh
- призрак
- Fantasma
- Santo
- 鬼
- Fantomo
- Kummitus
- Multo
- Aave
- Esprit
- Pantasma
- Geist
- φάντασμα
- મૃત માનવીનું પ્રેત
- Sentespri
- भूत
- Dab
- Szellem
- Hantu
MagmaCubeNames:
- Flibbach
- Blachby
- Blarhb
- Flarrbble
- Flarrber
- Fleehb
- Blirrb
- Blarrb
- Bloochh
- Ignis
- Magmë
- Maqma
- магма
- ম্যাগমা
- 岩浆
- Magmo
- મેગ્મા
- द्रुतपुंज
- マグマ
- ಶಿಲಾರಸ
- 광물의 연한 덩어리
- ज्यावर भूकवच तरंगत आहे असा पृथ्वीचा अंतर्भाग त्यातील द्रव्यापासून अग्निग्जन्य खडक बनतो
- Magmă
- அடர் குழம்பு
- భూగర్భములో వేడికి కరిగిపోయిన శిలాద్రవము
- หินหนืด
- Mağma
- Chất bầy nhầy
- kub
- խորանարդ
- Kubo
SilverfishNames:
- Vario
- Mr. Jiggles
- Squiggly
- Wiggle
- Wigglesworth
- Silver
- тарпон
- Lepisma
- 蠹虫
- Rybenky
- Sølvfisk
- Tisanuro
- Silberfischchen
- Lepism
- Silfurskottanna
- Gegat
- セイヨウシミ
- ಬೆಳ್ಳಿ ಮೀನು
- 벌레
- वाळवी
- Sølvkre
- Силверфисх
- Ščetinorepke
- Silverfisk
- Cá bạc
- Peshk
- ձուկ
- Balıq
- рыба
- মাছ
- Riba
- Geoff
SlimeNames:
- Flubber
- Blobby
- Blob
- Bob the Blob
- Flobble
- Flubber
- Floob
- Blib
- Blab
- Blaab
- Bloob
- Blub
- Slyk
- Zhul
- դուրս պրծնել
- Lil
- Lohi
- слізь
- Mulj
- тиня
- Llim
- 粘液
- Sliz
- Slijm
- ŝlimo
- Lima
- Lodo
- λάσπη
- લીંબુંનો
- कीचड़
- Iszap
SkeletonNames:
- Rattles
- Gunslinger
- Skeleton
- Skeletor
- Boney
- Bones
- You, after I've dealt with you.
- Parietal
- Occipital
- Sphenoid
- Ethmoid
- Mandible
- Maxilla
- Palatine
- Zygomatic
- Lacrimal
- Conchae
- Vomer
- Malleus
- Incus
- Stapes
- Hyoid
- Scapula
- Clavicle
- Sternum
- Gladiolus
- Manubruim
- Xiphoid
- Rib
- Lumbar
- Humerous
- Ulna
- Carpal
- Scaphoid
- Lunate
- Triquetrum
- Pisiform
- Trapezium
- Trapezoid
- Capitate
- Hamate
- Metacarpus
- Phalanges
- Sacrum
- Coccyx
- Coxae
- Femur
- Patella
- Tibia
- Fibula
- Tarsal
- Calcaneus
- Talus
- Navicular
- Cuneiform
- Cuboid
- Metatarsus
- Undead Archer
- Skeleton
SnowGolemNames:
- Frosty
- Melty
- Snowy
- Harold
- Bill
- Donald
- Bob
- Jeff
- Sam
- Frost
- Mr. Freeze
- Flake
- Vanilla Ice
- Bluster
- Frosty
- Borë
- ձյուն
- Qar
- Elurra
- снег
- তুষার
- Snijeg
- сняг
- Neu
- 雪
- Sníh
- Sne
- Sneeuw
- Lumi
- Neige
- Neve
SpiderNames:
- Black Widow
- Cellar
- Crab
- Brown Recluse
- Funnel Web
- Brown Recluse
- Man
- Tarantula
- Spidey
- Arachnid
- Merimangë
- սարդ
- Hörümçək
- Armiarma
- павук
- মাকড়সা
- Pauk
- паяк
- Aranya
- 蜘蛛
- Pauk
- Pavouk
- Spin
- Araneo
- ämblik
- Gagamba
- Hämähäkki
- Araignée
- Araña
- Spinne
- αράχνη
WitchNames:
- Wicked Witch of the West
- Grimhilde
- The Witch of Endor
- Maleficent
- Heks
- Magjistare
- կախարդ
- Ifritə
- Ведзьма
- জাদুকরী
- Vještica
- вещица
- Bruixa
- Barangan
- 巫婆
- čarodějnice
- Sorcxistinon
- Nõid
- Bruha
- Noita
- Sorcière
- Bruxa
- Hexe
- μάγισσα
- ચૂડેલ
- Sòsyè
- डायन
- Boszorkány
- Norn
- Penyihir
- Cailleach
WitherNames:
- Aleksander
- Vinter
- Wither
- JIMJUM 2.0
- Verwelk
- Thahet
- թառամել
- ölmək
- вянуць
- নির্জীব করা
- Uvenuti
- вехна
- Marcir
- Malaya
- 枯萎
- Vysušit
- Visne
- Verdorren
- Forvelkas
- Närbuma
- Makalanta
- Lakastua
- Dessécher
- Murchar
- წაიშალოს
- Verkümmern
- μαραίνω
- કરમાવું
- Fennen
- कुम्हलाना
- Elhervad
ZombieNames:
- Bob
- Hilda
- ZOMG
- Zomble
- Zomboy
- Zombow
- Zomble
- Trololololol
- BRAINZZZZ......
- Brainnnnns.....
- Uh
- Guh
- Uhhhhhh...
- Sid
- Uhh
- UHHHHHHHHHH
- Sid
- Corpus
- Gobblebrain
- BLEEEURGHHH
- Gobbler
- Corpicus the Brainless
- Ssmfox
- Tristan
- Draugr
- Mumje
- зомбі
- বোকচন্দর
- Zombi
- новобранец
- 僵尸
VillagerNames:
- Harry
- Jack
- Oliver
- Charlie
- James
- George
- Thomas
- Ethan
- Jacob
- William
- Daniel
- Joshua
- Max
- Noah
- Alfie
- Samuel
- Dylan
- Oscar
- Lucas
- Aidan
- Isaac
- Riley
- Henry
- Banjamin
- Joseph
- Alexander
- Lewis
- Leo
- Tyler
- Jayden
- Zac
- Freddie
- Archie
- Logan
- Adam
- Ryan
- Nathan
- Matthew
- Sebastian
- Jake
- Toby
- Alex
- Luke
- Liam
- Harrison
- David
- Jamie
- Edward
- Luca
- Elliot
- Aaron
- Finley
- Michael
- Zachary
- Mason
- Sam
- Mohammed
- Connor
- Ben
- Reuben
- Theo
- Rhys
- Arthur
- Caleb
- Dexter
- Rory
- Jenson
- Evan
- Gabriel
- Ewan
- Callum
- Seth
- Felix
- Austin
- Owen
- Leon
- Cameron
- Jude
- Harley
- Blake
- Harvey
- Tom
- Hugo
- Finn
- Bobby
- Hayden
- Kyle
- Jasper
- Tommy
- Eli
- Kian
- Andrew
- John
- Louie
- Dominic
- Joe
- Elijah
- Kai
- Frankie
- Stanley
- Amelia
- Lily
- Emily
- Sophia
- Isabelle
- Sophie
- Olivia
- Jessica
- Chloe
- Mia
- Isla
- Isabella
- Ava
- Charlotte
- Grace
- Evie
- Poppy
- Lucy
- Ella
- Holly
- Emma
- Molly
- Annabelle
- Erin
- Freya
- Ruby
- Scarlett
- Alice
- Layla
- Hannah
- Eva
- Imogen
- Millie
- Daisy
- Abigail
- Amy
- Zoe
- Megan
- Maisie
- Phoebe
- Maya
- Anna
- Eliza
- Caitlin
- Amelie
- Jasmine
- Florence
- Sienna
- Madison
- Elanor
- Darcey
- Lola
- Elizabeth
- Leah
- Matilda
- Summer
- Elsie
- Ellie
- Zara
- Rosie
- Kayla
- Esme
- Amber
- Georgia
- Bethany
- Rose
- Evelyn
- Lexi
- Niamh
- Katie
- Alyssa
- Lauren
- Heidi
- Gracie
- Skye
- Willow
- Faith
- Beth
- Alexandra
- Iris
- Harriet
- Violet
- Lara
- Martha
- Rebecca
- Seren
- Gabriella
- Tilly
- Naomi
- Sarah
- Clara
- Nicole
- Elise
- Mila
- Annie
- Sara
- Bella
- Francesca
- Elena
- Libby
- Robert
- Rick
- Wout
- Taylor
- Christopher
ZombiePigmanNames:
- Zoink
- Gurrrrrr
- Bernie
- Jim
- Bob
- Grghhhh
- Guh
- свінаводам
- Пигман
- Porquero
- 皮格曼
- 