# Allwaysshowtags doesn't affect mobs which have already spawned! Use the "SetVisibility" command to change those.
a_settings:
   allwaysshowtags: true #doesn't affect mobs allready spawned! Use the setvisibility command to change those.
BatNames:
- Man
- Rouge
- Flutter Me Timbers
- Batty
- Dracula
- Batt
- Bob the Bat
- Fang
- Vlad
- Batosity
- Al-Ghul
- Nosferatu
- Fledermaus
- Bitey
- Diablerie
- Bella
- Max
- Lee
- Tony
- Bax
- Lucifer
- Dullus
- Skotardus
- Thanatos
- Mortus
- Tenebrus
- Noisy
- Charline
- Rosfrath
- Bastion
- Luna
- Maya
- Mayotis
- Batrisha
- Ralph
- Bertie
ChickenNames:
- Picasso
- Fingerlicken
- Licken
- Batter
- Dinner
- Lunch
- Foghorn
- Leghorn
- Boo
- Alfred
- Ginger
- Camilla
- Robot
- Cluck
- Clucky
- Mike
- Rocky
- Gregory
- Peck
- Little
- Penny
- Rubber
- Nugget
- Leg
- Wing
- Fried
- Kentucky
- Toktok
- Flatfoot
CowNames:
- Gertrude
- Bessie
- Whack Angus
- Angus
- Whack
- Beefy
- Ermintrude
- Colleen
- Betsy
- Patty
- Anna
- Molly
- Darcy
- Elli
- Ethel
- Nelly
- Beth
- Daisy
- Buttercup
- Achelous
- Audhumla
- Bat
- Blue
- Bully
- Chaldan
- Damona
- Dhol
- Dun
- Elsie
- Flossie
- Fuwch
- Glas
- Hathor
- Hesat
- Lo
- Mehturt
- Milka
- Nandini
- Sechat
- Sentait
- Taurus
- Vache
- Annabelle
- Klara
- June
- Johnny
- Kate
- Boy
- Dixie
- Marigold
IronGolemNames:
- Fat Tony
- Bruce
- Cranky
- Nutty
- Bolts
- Bouncer
- Bob
- Jim
- Defender
- Protector
- Cranky
- Rob
- Boris
- Clunk
- Clank
- Clang
- Pummela
- Thonk
- Thumper
- Sergeant
- Bash
- Norton
- Eibmoz
- Slam
- Thwomp
- Chef
- Steelton
- Homie McSteel
- Johnny Iron
- Red Five
- Android 16
MooshroomNames:
- Ultus
- Ulti
- Red
- Fungus
- Awesomnitetric
- Ermintruffle
OcelotNames:
- Tiddles
- Tigger
- Fluffy
- Oscar
- Max
- Tiger
- Sam
- Misty
- Simba
- Coco
- Chloe
- Lucy
- Missy
- Puss
- Smokey
- Bella
- Molly
- Milo
- Angel
- Lily
- Kitty
- Ginger
- Charlie
- Poppy
- Smudge
- Millie
- Daisy
- Jasper
- Felix
- Alfie
- Shadow
- Minka
- Moritz
- Charly
- Susi
- Lisa
- Blacky
- Muschi
- Minou
- Grisou
- Ti-Mine
- Caramel
- Mimi
- Pacha
- Charlotte
- Minette
- Chanel
- Dama
- Ancella
- Briseide
- Folco
- Jack
- Barsik
- Boris
- Vaska
PigNames:
- Porky
- Piggy
- Miss Piggy
- Pumba
- Wilbur
- Hamm
- Percy
- Peppa
- Ace
- Fener
- Freddy
- Gaston
- Josephine
- Gouger
- Snouter
- Rooter
- Tusker
- Gryllus
- Gub
- Habeas
- Hamilton
- Hen
- Henry
- Jodie
- Johnny
- Jimmy
- Jaimie
- Jared
- Jason
- Justin
- Karnac
- Kimmy
- Lester
- Robinson
- Mercy
- Napoleon
- Major
- Olivia
- Pequenious
- Pig
- Pigling
- Pigoons
- Poppleton
- Positive
- Piggy
- Rumbl
- Rwoar
- Sam
- Snowball
- Squealer
- Toby
- Toot
- Puddle
- Zhu
SheepNames:
- Dolly
SquidNames:
- Squidlington
- Squidward
- Squiddles
- Kraken
- Ood
WolfNames:
- Bach
- Wolfgang
- Max
- Buddy
- Molly
- Maggie
- Jake
- Daisy
- Lucy
- Rocky
- Bailey
- Sadie
- Ginger
- Chloe
- Sophie
- Buster
- Zoe
- Cody
- Charlie
- Bear
- Jack
- Princess
- Bella
- Angel
- Toby
- Lady
- Sasha
- Duke
- Lucky
- Abby
- Sam
- Roxy
- Missy
- Harley
- Brandy
- Coco
- Shadow
- Annie
- Katie
- Rusty
- Samantha
- Casey
- Murphy
- Gracie
- Sammy
- Bruno
- Maximus
- Luke
- Mickey
- Romeo
BlazeNames:
- Death
- Firestarter
- Burnie
- Fire Breather
- Firefly
CaveSpiderNames:
- Black Widow
- Cellar
- Crab
- Brown Recluse
- Funnel Web
- Brown Recluse
- Man
- Tarantula
CreeperNames:
- JIMJUM - Green Edition
- Mr. T... NT
- Sir Creepalot
- ssssSSSSSSS
- Creeps
- Creepy
- Creepah
- It'll be fine...
- James
- Bertie
- Creeples
- Come closer...
- I just want a hug...
- Boomer
- Rick Asssssssstley
- Da Bomb
- I'm a cow really... come closer...
- Cuddlesssssssss
- Ssssssssteve
EnderDragonNames:
- GAHHHHHHD
- Santa Claus
- I'muh DRAYYGON
- Your eventual cause of Death...
EndermanNames:
- Old Longlegs
- Daddy longlegs
- By the time you've read this I'm probably already chasing you...
- No.
- Gerroff muy laaarnd!
- Stares
- Look down...
- End
- Endy
- Endus
- Endus McEnd
- The Face Of Death
- Look into my eyes...
- Bob
- John
- Ender Claus
- Rick
- Miles
- Jeff
GhastNames:
- Floating Paper Bag
- Hilda
- Testifighast
- Ghoul
- Ghost
- Ghast
MagmaCubeNames:
- Flibbach
- Blachby
- Blarhb
- Flarrbble
- Flarrber
- Fleehb
- Blirrb
- Blarrb
- Bloochh
- Ignis
SilverfishNames:
- Vario
- Mr. Jiggles
- Squiggly
- Wiggle
- Wigglesworth
- I'm neither a fish, nor silver.
SlimeNames:
- Flubber
- Blobby
- Blob
- Bob the Blob
- Flobble
- Flubber
- Floob
- Blib
- Blab
- Blaab
- Bloob
- Blub
SkeletonNames:
- Rattles
- Gunslinger
- Skeleton
- Skeletor
- Boney
- Bones
- You, after I've dealt with you.
- Parietal
- Occipital
- Sphenoid
- Ethmoid
- Mandible
- Maxilla
- Palatine
- Zygomatic
- Lacrimal
- Conchae
- Vomer
- Malleus
- Incus
- Stapes
- Hyoid
- Scapula
- Clavicle
- Sternum
- Gladiolus
- Manubruim
- Xiphoid
- Rib
- Lumbar
- Humerous
- Ulna
- Carpal
- Scaphoid
- Lunate
- Triquetrum
- Pisiform
- Trapezium
- Trapezoid
- Capitate
- Hamate
- Metacarpus
- Phalanges
- Sacrum
- Coccyx
- Coxae
- Femur
- Patella
- Tibia
- Fibula
- Tarsal
- Calcaneus
- Talus
- Navicular
- Cuneiform
- Cuboid
- Metatarsus
- Undead Archer
- Skeleton
SnowGolemNames:
- Frosty
- Melty
- Snowy
- Harold
- Bill
- Donald
- Bob
- Jeff
- Sam
- Frost
- Mr. Freeze
- Flake
- Vanilla Ice
- Bluster
- Frosty
SpiderNames:
- Black Widow
- Cellar
- Crab
- Brown Recluse
- Funnel Web
- Brown Recluse
- Man
- Tarantula
WitchNames:
- Wicked Witch of the West
- Grimhilde
- The Witch of Endor
- Maleficent
WitherNames:
- Aleksander
- Vinter
- Wither
ZombieNames:
- Bob
- Hilda
- ZOMG
- Zomble
- Zomboy
- Zombow
- Zomble
- Trololololol
- BRAINZZZZ......
- Brainnnnns.....
- Uh
- Guh
- Uhhhhhh...
- Sid
- Uhh
- UHHHHHHHHHH
- Sid
- Corpus
- Gobblebrain
- BLEEEURGHHH
- Gobbler
- Corpicus the Brainless
- Ssmfox
- Tristan
- Draugr
VillagerNames:
- Harry
- Jack
- Oliver
- Charlie
- James
- George
- Thomas
- Ethan
- Jacob
- William
- Daniel
- Joshua
- Max
- Noah
- Alfie
- Samuel
- Dylan
- Oscar
- Lucas
- Aidan
- Isaac
- Riley
- Henry
- Banjamin
- Joseph
- Alexander
- Lewis
- Leo
- Tyler
- Jayden
- Zac
- Freddie
- Archie
- Logan
- Adam
- Ryan
- Nathan
- Matthew
- Sebastian
- Jake
- Toby
- Alex
- Luke
- Liam
- Harrison
- David
- Jamie
- Edward
- Luca
- Elliot
- Aaron
- Finley
- Michael
- Zachary
- Mason
- Sam
- Muhammad
- Connor
- Ben
- Reuben
- Theo
- Rhys
- Arthur
- Caleb
- Dexter
- Rory
- Jenson
- Evan
- Gabriel
- Ewan
- Callum
- Seth
- Felix
- Austin
- Owen
- Leon
- Cameron
- Jude
- Harley
- Blake
- Harvey
- Tom
- Hugo
- Finn
- Bobby
- Hayden
- Kyle
- Jasper
- Tommy
- Eli
- Kian
- Andrew
- John
- Louie
- Dominic
- Joe
- Elijah
- Kai
- Frankie
- Stanley
- Amelia
- Lily
- Emily
- Sophia
- Isabelle
- Sophie
- Olivia
- Jessica
- Chloe
- Mia
- Isla
- Isabella
- Ava
- Charlotte
- Grace
- Evie
- Poppy
- Lucy
- Ella
- Holly
- Emma
- Molly
- Annabelle
- Erin
- Freya
- Ruby
- Scarlett
- Alice
- Layla
- Hannah
- Eva
- Imogen
- Millie
- Daisy
- Abigail
- Amy
- Zoe
- Megan
- Maisie
- Phoebe
- Maya
- Anna
- Eliza
- Caitlin
- Amelie
- Jasmine
- Florence
- Sienna
- Madison
- Elanor
- Darcey
- Lola
- Elizabeth
- Leah
- Matilda
- Summer
- Elsie
- Ellie
- Zara
- Rosie
- Kayla
- Esme
- Amber
- Georgia
- Bethany
- Rose
- Evelyn
- Lexi
- Niamh
- Katie
- Alyssa
- Lauren
- Heidi
- Gracie
- Skye
- Willow
- Faith
- Beth
- Alexandra
- Iris
- Harriet
- Violet
- Lara
- Martha
- Rebecca
- Seren
- Gabriella
- Tilly
- Naomi
- Sarah
- Clara
- Nicole
- Elise
- Mila
- Annie
- Sara
- Bella
- Francesca
- Elena
- Libby
- Robert
- Rick
- Wout
- Taylor
- Christopher
ZombiePigmanNames:
- Zoink
- Gurrrrrr
- Bernie
- Jim
- Bob
- Grghhhh
- Guh
